//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UbiCom.Net.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorString() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UbiCom.Net.Resources.ErrorString", typeof(ErrorString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   이미 Connected 상태입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AlreadyConnected {
            get {
                return ResourceManager.GetString("AlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   환경 설정 값이 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigurationIsNull {
            get {
                return ResourceManager.GetString("ConfigurationIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration File이 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DoseNotExistConfigurationFile {
            get {
                return ResourceManager.GetString("DoseNotExistConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UMD File에 정의된 Message가 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DoseNotExistDefinedMessageSet {
            get {
                return ResourceManager.GetString("DoseNotExistDefinedMessageSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Driver 이름이 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DoseNotExistDriverName {
            get {
                return ResourceManager.GetString("DoseNotExistDriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UMD File이 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DoseNotExistUMDFile {
            get {
                return ResourceManager.GetString("DoseNotExistUMDFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   처리되지 않은 예외가 발생했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExceptionOccurrence {
            get {
                return ResourceManager.GetString("ExceptionOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration File Load를 실패했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FailedConfigurationFileLoad {
            get {
                return ResourceManager.GetString("FailedConfigurationFileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configuration File Save를 실패했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FailedConfigurationFileSave {
            get {
                return ResourceManager.GetString("FailedConfigurationFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port Open에 실패했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FailedPortOpen {
            get {
                return ResourceManager.GetString("FailedPortOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UMD File Load를 실패했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FailedUMDFileLoad {
            get {
                return ResourceManager.GetString("FailedUMDFileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP Address 설정 값이 올바르지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidIPAddress {
            get {
                return ResourceManager.GetString("InvalidIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port No 설정 값이 올바르지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidPortNo {
            get {
                return ResourceManager.GetString("InvalidPortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout 설정 값이 올바르지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidTimeout {
            get {
                return ResourceManager.GetString("InvalidTimeout", resourceCulture);
            }
        }
    }
}
