//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UbiGEM.Net.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XML {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XML() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UbiGEM.Net.Resources.XML", typeof(XML).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;PreDefined&gt;
        ///  &lt;CEIDList&gt;
        ///    &lt;CEID ID=&quot;1&quot; Name=&quot;Offline&quot; Description=&quot;Offline&quot; IsBase=&quot;false&quot; /&gt;
        ///    &lt;CEID ID=&quot;18&quot; Name=&quot;OfflineOnHost&quot; Description=&quot;Offline on HOST&quot; IsBase=&quot;false&quot; /&gt;
        ///    &lt;CEID ID=&quot;2&quot; Name=&quot;OnlineLocal&quot; Description=&quot;Online Local&quot; IsBase=&quot;false&quot; /&gt;
        ///    &lt;CEID ID=&quot;3&quot; Name=&quot;OnlineRemote&quot; Description=&quot;Online Remote&quot; IsBase=&quot;false&quot; /&gt;
        ///    &lt;CEID ID=&quot;4&quot; Name=&quot;ControlStateChanged&quot; Description=&quot;Control State Changed&quot; IsBase=&quot;false&quot; /&gt;
        ///    &lt;CEID ID=&quot;5&quot; [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PreDefined {
            get {
                return ResourceManager.GetString("PreDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;MessageList&gt;
        ///  &lt;SECSMessage&gt;
        ///    &lt;Header&gt;
        ///      &lt;MessageName&gt;AreYouThere&lt;/MessageName&gt;
        ///      &lt;Stream&gt;1&lt;/Stream&gt;
        ///      &lt;Function&gt;1&lt;/Function&gt;
        ///      &lt;Direction&gt;Both&lt;/Direction&gt;
        ///      &lt;WaitBit&gt;true&lt;/WaitBit&gt;
        ///      &lt;AutoReply&gt;false&lt;/AutoReply&gt;
        ///      &lt;NoLogging&gt;false&lt;/NoLogging&gt;
        ///      &lt;Description&gt;Are You There Request&lt;/Description&gt;
        ///    &lt;/Header&gt;
        ///    &lt;DataItem /&gt;
        ///  &lt;/SECSMessage&gt;
        ///  &lt;SECSMessage&gt;
        ///    &lt;Header&gt;
        ///      &lt;MessageName&gt;OnLineData&lt;/MessageName&gt;
        ///   [나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StandardMessageStructure {
            get {
                return ResourceManager.GetString("StandardMessageStructure", resourceCulture);
            }
        }
    }
}
